// Ограждения: линии, конструкция, столбы, заполнение, крышки, материалы
// (src/fences, sections/fences.jsx). Одна ведомость и одна геометрия на сцену и отчёт.
const style = (key, ru, en) => [`fenceObjects[].segments[].style.${key}`, [ru, en]];
export default Object.fromEntries([
  ['fencesEnabled', ['Ограждения в кадре. Выключатель прячет их, не удаляя; ведомость и отчёт считают только включённые.', 'Fences in the frame. The switch hides them without deleting; the schedule and the report count only fences switched on.']],
  ['fenceObjects', ['Какую линию ограждения выбрать: кадр подъедет к ней. Линии рисуются инструментом «Ограда» щелчками по земле или модели; двойной щелчок по участку делит его.', 'Which fence path to select: the view moves to it. Paths are drawn with the Fence tool by clicks on the ground or the model; a double click on a segment splits it.']],
  style('type', 'Конструкция выбранных участков: сетка, дерево вертикально или горизонтально, металлические профили, бетонная или кирпичная стена, только столбы. Каждая — свои поля ниже.', 'Construction of the selected segments: mesh, timber vertical or horizontal, metal profiles, a concrete or brick wall, posts only. Each shows its own fields below.'),
  style('height', 'Высота ограждения от земли до верха заполнения, м. Столбы могут быть выше — «Столб выше заполнения».', 'Fence height from the ground to the top of the infill, m. Posts may rise higher — see “Post above infill”.'),
  style('spacing', 'Наибольший шаг столбов, м: участок делится на равные пролёты не длиннее этого. От шага зависят число столбов и лаг в ведомости.', 'The largest post spacing, m: a segment is split into equal bays no longer than this. It sets the count of posts and rails in the schedule.'),
  style('offset', 'Дополнительный сдвиг ограждения от нарисованной линии, м, поверх положения к оси. Плюс — вправо по ходу линии.', 'Extra shift of the fence from the drawn path, m, on top of the position to axis. Positive — to the right along the path.'),
  style('clearance', 'Просвет между землёй и низом заполнения, м. У стен — ноль, у сетки и штакетника — несколько сантиметров.', 'Gap between the ground and the bottom of the infill, m. Zero for walls, a few centimetres for mesh and pickets.'),
  style('alignment', 'Где стоит ограждение относительно нарисованной линии: по оси, слева или справа по ходу (у замкнутого контура — внутри или снаружи). Линия остаётся границей участка.', 'Where the fence stands against the drawn path: on the axis, left or right along it (inside or outside for a closed loop). The path stays the site boundary.'),
  style('grade', 'Как ограждение идёт по уклону: верх повторяет рельеф, ступенями по пролётам или единый горизонтальный верх на весь участок.', 'How the fence follows a slope: the top follows the ground, steps bay by bay, or one level top for the whole segment.'),
  style('up', 'Куда растёт высота: строго вертикально или по нормали поверхности модели, если ограждение стоит на её скате.', 'Which way the height goes: strictly vertical, or along the surface normal when the fence stands on a slope of the model.'),
  style('thickness', 'Толщина бетонной или кирпичной стены, м. На заполнение других конструкций не влияет.', 'Thickness of a concrete or brick wall, m. Other constructions ignore it.'),
  style('postEnabled', 'Ставить ли столбы. Без них заполнение висит само по себе — для стен и эскизов; в ведомости столбов тогда нет.', 'Whether to place posts. Without them the infill stands on its own — for walls and sketches; the schedule then lists no posts.'),
  style('postKind', 'Из чего столб: металл, дерево, бетон или кладка. Определяет типовые сечения в списке ниже и строку ведомости.', 'What the post is made of: metal, timber, concrete or masonry. It picks the stock sections in the list below and the schedule line.'),
  style('postStock', 'Типовое сечение столба из сортамента: выбор сразу заполняет ширину, глубину и стенку профиля. Своё — оставить и править поля вручную.', 'A stock post section: choosing one fills the width, depth and wall thickness at once. Custom — leave it and edit the fields by hand.'),
  style('postWidth', 'Ширина столба поперёк линии, м.', 'Post width across the path, m.'),
  style('postDepth', 'Глубина столба вдоль линии, м.', 'Post depth along the path, m.'),
  style('postWall', 'Толщина стенки профиля столба, м: для трубы и швеллера. Ноль — сплошной столб.', 'Wall thickness of the post profile, m: for tubes and channels. Zero — a solid post.'),
  style('postExtra', 'Насколько столб выше верха заполнения, м.', 'How far the post rises above the top of the infill, m.'),
  style('memberStock', 'Типовое сечение планки из сортамента: выбор заполняет ширину, толщину и стенку. Своё — править поля вручную.', 'A stock member section: choosing one fills the width, depth and wall. Custom — edit the fields by hand.'),
  style('memberWidth', 'Ширина планки заполнения (доски, штакетины, профиля), м.', 'Width of an infill member (a board, a picket, a profile), m.'),
  style('memberDepth', 'Толщина планки заполнения, м.', 'Thickness of an infill member, m.'),
  style('memberWall', 'Толщина стенки профиля планки, м: для металлических труб. Ноль — сплошная планка.', 'Wall thickness of the member profile, m: for metal tubes. Zero — a solid member.'),
  style('memberGap', 'Зазор между планками, м. Ноль — сплошное полотно.', 'Gap between members, m. Zero — a solid screen.'),
  style('railCount', 'Сколько лаг в пролёте держат заполнение. Лаги идут от столба к столбу и попадают в ведомость метрами.', 'How many rails per bay carry the infill. Rails run post to post and enter the schedule in metres.'),
  style('railWidth', 'Высота сечения лаги, м.', 'Height of the rail section, m.'),
  style('railDepth', 'Толщина лаги, м.', 'Thickness of the rail, m.'),
  style('railWall', 'Толщина стенки профиля лаги, м: для металлических труб. Ноль — сплошная лага.', 'Wall thickness of the rail profile, m: for metal tubes. Zero — a solid rail.'),
  style('wire', 'Диаметр проволоки сетки, м.', 'Wire diameter of the mesh, m.'),
  style('cellWidth', 'Ширина ячейки сетки, м.', 'Mesh cell width, m.'),
  style('cellHeight', 'Высота ячейки сетки, м.', 'Mesh cell height, m.'),
  style('caps', 'Крышки на столбах: закрывают торец от воды. Считаются в ведомости поштучно.', 'Caps on the posts: they close the end against water. The schedule counts them per piece.'),
  style('capHeight', 'Высота крышки столба, м.', 'Height of the post cap, m.'),
  style('capOverhang', 'Свес крышки за грань столба, м.', 'Cap overhang beyond the post face, m.'),
  style('tile', 'Масштаб материала на ограждении: во сколько раз крупнее или мельче класть его плитку. 1 — как в библиотеке.', 'Material scale on the fence: how much larger or smaller its tile is laid. 1 — as in the library.'),
  style('panelMaterial', 'Материал заполнения из библиотеки. «По конструкции» — цвет самой конструкции.', 'Infill material from the library. “Construction” — the colour of the construction itself.'),
  style('postMaterial', 'Материал столбов из библиотеки. «По конструкции» — цвет по материалу столба.', 'Post material from the library. “Construction” — the colour of the post material.'),
  style('railMaterial', 'Материал лаг из библиотеки. «По конструкции» — цвет самой конструкции.', 'Rail material from the library. “Construction” — the colour of the construction itself.'),
  style('capMaterial', 'Материал крышек из библиотеки. «По конструкции» — как у столбов.', 'Cap material from the library. “Construction” — as the posts.'),
]);
