// Огонь использует общие подсказки редактора; точки — в местной раме следа.
export default {
  fireEnabled: ['Показывает колею, огонь и дым на суше. Сам рельеф и его настройки не меняются.', 'Shows the trail, fire and smoke on land. Terrain and its settings stay unchanged.'],
  firePointCount: ['Число опорных точек сплайна. Между ними колея изгибается плавно.', 'Number of spline control points. The trail curves smoothly between them.'],
  fireEditPoint: ['0 — двигать весь след; номер точки — двигать только её ручку в сцене.', '0 moves the whole trail; a point number moves only that point with the scene handle.'],
  ...Object.fromEntries(Array.from({ length: 12 }, (_, i) => ['X', 'Z'].map((axis) => [`fireP${i + 1}${axis}`, [`Точка ${i + 1}: координата ${axis} внутри рамы следа, м. Высота следует за землёй.`, `Point ${i + 1}: local ${axis} coordinate in the trail frame, metres. Height follows the ground.`]])).flat()),
  fireX: ['Перенос всего следа по мировой оси X, м. Опорные точки сохраняют взаимное положение.', 'Moves the entire trail along world X, metres. Control points keep their relative positions.'],
  fireZ: ['Перенос всего следа по мировой оси Z, м. Высота берётся из поверхности земли.', 'Moves the entire trail along world Z, metres. Height comes from the ground surface.'],
  fireYaw: ['Поворот всего следа вокруг вертикали, градусы.', 'Rotation of the whole trail around the vertical axis, degrees.'],
  fireScale: ['Общий масштаб траектории относительно её центра. Форма сплайна сохраняется.', 'Scales the trail path about its centre while preserving the spline shape.'],
  fireDelay: ['Задержка до первого поджига в цикле, секунды.', 'Delay before the first ignition in a cycle, seconds.'],
  fireSpeed: ['Скорость фронта огня вдоль колеи, м/с.', 'Speed of the fire front along the trail, metres per second.'],
  fireBurn: ['Сколько секунд горит каждый участок. 0 — пройденный огнём след не гаснет до конца цикла.', 'Seconds each section burns. 0 keeps the ignited trail burning until the cycle ends.'],
  fireLoop: ['Повторяет поджиг после окончания прохода и паузы.', 'Repeats ignition after the pass and the loop pause have ended.'],
  fireLoopPause: ['Пауза между повторными проходами огня, секунды.', 'Pause between repeated fire passes, seconds.'],
  fireWidth: ['Ширина горящей полосы на земле, метры.', 'Width of the burning strip on the ground, metres.'],
  fireHeight: ['Высота языков пламени над следом, метры.', 'Height of the flames above the trail, metres.'],
  fireIntensity: ['Яркость пламени. Освещение земли настраивается отдельно.', 'Brightness of the flames. Illumination of the ground is controlled separately.'],
  fireTurbulence: ['Сила неровных движений и изгибов пламени.', 'Strength of irregular motion and bending in the flames.'],
  fireColorHot: ['Цвет горячего ядра у основания пламени.', 'Colour of the hot core near the flame base.'],
  fireColorCool: ['Цвет более холодных краёв и концов языков.', 'Colour of the cooler edges and tips of the flames.'],
  fireSmoke: ['Показывает дым над горящей полосой.', 'Shows smoke above the burning strip.'],
  fireSmokeAmount: ['Количество дымовых частиц в пределах бюджета качества.', 'Number of smoke particles within the quality budget.'],
  fireSmokeRise: ['Скорость подъёма дыма над землёй.', 'Speed at which smoke rises above the ground.'],
  fireSmokeLife: ['Время жизни клубов дыма, секунды.', 'Lifetime of smoke puffs, seconds.'],
  fireSmokeSize: ['Размер отдельных клубов дыма.', 'Size of individual smoke puffs.'],
  fireSmokeWind: ['Насколько дым уносит общий ветер берега.', 'How strongly the shared coastal wind carries the smoke.'],
  fireSmokeColor: ['Базовый цвет дыма до освещения небом и огнём.', 'Base smoke colour before lighting from the sky and fire.'],
  fireSmokeOpacity: ['Плотность дыма: больше — сильнее закрывает фон.', 'Smoke opacity: higher values obscure the background more.'],
  fireLight: ['Включает свет у фронта огня. Дополнительных теней этот свет не создаёт.', 'Enables a light at the fire front. This light does not cast additional shadows.'],
  fireLightIntensity: ['Сила света от огня на окружающих поверхностях.', 'Strength of fire light on surrounding surfaces.'],
  fireLightDistance: ['Дальность света от фронта огня, метры.', 'Reach of the light at the fire front, metres.'],
  fireTrack: ['Показывает колею, горючее и след копоти на земле.', 'Shows the track, fuel and soot trail on the ground.'],
  fireTrackDark: ['Насколько колея и горючее темнее окружающего грунта.', 'How dark the track and fuel appear against the surrounding ground.'],
  fireSootFade: ['За сколько секунд исчезает копоть. 0 — остаётся до перезапуска цикла.', 'Seconds before soot fades. 0 keeps it until the cycle restarts.'],
};
