// Подсказки «?» к параметрам Bikini Point: дом на сваях, сарай и вещи
// серферов (components/house). Ключ — ключ параметра в справочнике
// (docs/engine-parameters.json), значение — [по-русски, in English].
const paint = (ru, en) => [
  `Цвет: ${ru}. Текстуры дерева и краски им подкрашиваются, подтёки и выцветание ложатся поверх.`,
  `Colour of ${en}. The wood and paint textures are tinted by it; streaks and fading lie on top.`,
];
const thing = (ru, en) => [
  `Цвет: ${ru}. «Оттенок вещей» и «Выгорание» потом поворачивают и выбеливают и его.`,
  `Colour of ${en}. “Hue of the things” and “Sun fading” then turn and bleach it too.`,
];
export default {
  houseEnabled: [
    'Bikini Point — дом на сваях, сарай, гирлянды и вещи серферов. Стоит на грунте; вдали сам становится проще, вещи вдали прячутся.',
    'Bikini Point — a house on stilts, its shed, the string lights and the surfers’ things. Stands on the ground; far off it simplifies itself and the things hide.',
  ],
  houseX: ['Где стоит середина дома по оси X, м; высоту берёт от грунта. Общая для всех камер.', 'Where the middle of the house stands along X, m; its height comes from the ground. Shared by every camera.'],
  houseZ: ['Где стоит середина дома по оси Z, м; высоту берёт от грунта. Общая для всех камер.', 'Where the middle of the house stands along Z, m; its height comes from the ground. Shared by every camera.'],
  houseHeading: ['Куда дом смотрит верандой, в градусах. Сарай и вещи поворачиваются вместе с ним.', 'Which way the porch faces, in degrees. The shed and the things turn with it.'],
  houseWidth: ['Ширина дома по фронтону, м. Окна, двери и веранда перестраиваются под новую ширину.', 'Width of the house across the gable, m. Windows, doors and the porch rebuild to fit.'],
  houseLength: ['Длина дома вдоль конька, м. Боковая веранда и пристройка растут вместе с ним.', 'Length of the house along the ridge, m. The side porch and the lean-to grow with it.'],
  houseFloorHeight: ['Высота пола над песком — длина свай, м. Лестница сама пересчитывает ступени по 15–19 см.', 'Floor height above the sand — the stilts, m. The stairs recount their 15–19 cm steps by themselves.'],
  houseRoofPitch: ['Уклон главной крыши, в градусах: круче — выше конёк и чердак.', 'Pitch of the main roof, in degrees: steeper raises the ridge and the attic.'],
  housePorchDepth: ['Глубина веранды от стены до столбов, м. Крыша веранды всегда уходит под окна второго этажа.', 'Depth of the porch from the wall to the posts, m. Its roof always passes under the upper windows.'],
  houseWeather: ['Подтёки под свесами и подоконниками, выцветшая и облезлая краска, ржавчина, мох. 0 — как новый.', 'Streaks under the eaves and sills, faded and peeling paint, rust, moss. 0 is as new.'],
  houseDamage: ['Сломанные и висящие доски, дыры в обшивке и крыше, выбитые стёкла, доски на песке. Больше — только добавляет поломок.', 'Broken and hanging boards, holes in the siding and roof, cracked panes, planks on the sand. More only adds to the damage.'],
  houseSag: ['Дом оседает на один угол, конёк провисает, веранда прогибается между столбами. 0 — всё ровно.', 'The house settles towards a corner, the ridge swaybacks, the porch sags between its posts. 0 keeps it true.'],
  houseSeed: ['Вариант рукотворной неровности: какие доски чуть кривее и какие ломает время. Одно число — один и тот же дом.', 'Which hand-made unevenness: which boards run a little off and which the years break. One number, one house.'],
  houseSidingColor: paint('обшивка стен', 'the clapboard'),
  houseShakesColor: paint('дранка пристройки', 'the lean-to’s shakes'),
  houseTrimColor: paint('белые доски: столбы, перила, лестница, наличники', 'the white boards: posts, rails, stairs, casings'),
  houseDeckColor: paint('настил веранды', 'the porch decking'),
  houseWoodColor: paint('сваи, юбка и каркас', 'the stilts, skirting and frame'),
  houseRoofColor: paint('кровля', 'the roofing'),
  houseMetalColor: paint('профлист на пристройке и сарае', 'the corrugated iron'),
  houseGlassColor: paint('стёкла', 'the glass'),
  houseDoorColor: paint('двери', 'the doors'),
  houseAwningColor: paint('ставни на окнах', 'the shutters'),
  houseShedWallColor: paint('стены сарая', 'the shed’s walls'),
  houseShedRoofColor: paint('крыша сарая', 'the shed’s roof'),
  houseRopeColor: paint('верёвочные перила', 'the rope rails'),
  houseUnitColor: paint('кондиционер и счётчик', 'the air conditioner and meter'),
  houseVoidColor: paint('дыры, где нет досок и стёкол', 'the holes where boards and panes are gone'),
  houseLampColor: paint('стекло фонарей', 'the lantern glass'),
  houseShed: ['Бирюзовый сарай у подножия лестницы, с гирляндой к нему. Встаёт на свой участок грунта.', 'The turquoise shed off the foot of the stairs, a string of lights across to it. Sits on its own patch of ground.'],
  houseLamps: ['Свет в комнатах за окнами и фонари у дверей. Днём почти не видно, ночью горит и светит вокруг.', 'Light in the rooms behind the windows and the lanterns by the doors. Barely seen by day; by night it glows and lights what is near.'],
  houseGarlands: ['Гирлянды под крышей веранды и через двор к сараю. Ночью светятся ореолами; вдали остаются одни ореолы.', 'String lights under the porch roof and across to the shed. By night they glow with halos; far off only the halos remain.'],
  houseCamp: ['Доски, круги, таблички, шезлонги, флажки, гамак, бельё, автомат с напитками и занавеска в двери.', 'The boards, rings, signs, deck chairs, flags, hammock, washing, drinks machine and the curtain in the door.'],
  houseCampSeed: ['Как вещи разбросаны: куда прислонены доски, как висят круги, куда воткнуты флажки. Дом при этом не меняется.', 'How the things are thrown about: where the boards lean, how the rings hang, where the flags are stuck. The house stays as it is.'],
  houseCampWind: ['Ветер: флажки, бельё, занавеска, висячие таблички и гамак. 0 — полный штиль.', 'The wind in the flags, the washing, the curtain, the hanging signs and the hammock. 0 is dead calm.'],
  houseCampHue: ['Поворачивает цвета всех вещей по кругу оттенков, в градусах: красные круги станут синими, жёлтые — зелёными.', 'Turns the colours of all the things round the hue circle, in degrees: red rings go blue, yellow goes green.'],
  houseCampFade: ['Выгорание на солнце: краски вещей бледнеют и сереют. 0 — как новые.', 'Sun fading: the things’ colours pale and grey. 0 is as new.'],
  houseCampChairsColor: thing('шезлонги', 'the deck chairs'),
  houseCampHammockColor: thing('гамак', 'the hammock'),
  houseCampCurtainColor: thing('полосы занавески', 'the curtain’s stripes'),
  houseCampFlagsColor: thing('флажки', 'the flags'),
  houseCampMachineColor: thing('перед автомата', 'the drinks machine’s front'),
  houseCampMachineSideColor: thing('бока автомата', 'the drinks machine’s sides'),
};
