// Подсказки «?» к параметрам: скульптура, лодка, танкер, расстановка,
// плоскость, чайки, рыбы, кувшинки, водоросли. Ключ — ключ параметра в
// справочнике (docs/engine-parameters.json), значение — [по-русски, in English].
export default {
  // Скульптура
  sculptureVisible: ['Чёрная каменная скульптура на дне. Выключена — исчезает, и чайки на неё больше не садятся.', 'The black stone sculpture on the bed. Off: it disappears, and gulls no longer land on it.'],
  sculpturePositionX: ['Где стоит скульптура по оси X, м; высоту берёт от грунта. Хранится в камере отдельно для Desktop и Mobile, двигать можно и прямо в сцене.', 'Where the sculpture stands along X, m; its height comes from the ground. Kept per camera, separately for Desktop and Mobile; you can also drag it in the scene.'],
  sculpturePositionZ: ['Где стоит скульптура по оси Z, м; высоту берёт от грунта. Хранится в камере отдельно для Desktop и Mobile, двигать можно и прямо в сцене.', 'Where the sculpture stands along Z, m; its height comes from the ground. Kept per camera, separately for Desktop and Mobile; you can also drag it in the scene.'],
  sculptureRotationY: ['Поворот вокруг вертикальной оси, в градусах: какой стороной скульптура смотрит в камеру.', 'Turns it around the vertical axis, in degrees: which side of the sculpture faces the camera.'],
  sculptureRotationX: ['Наклон вперёд-назад, в градусах. Край основания при этом может уйти в грунт — поднимите «Отступом от дна».', 'Tilts it forward or back, in degrees. An edge of the base may sink into the ground — lift it with “Offset from Seabed”.'],
  sculptureRotationZ: ['Крен вбок, в градусах. Как и наклон, может утопить край основания в грунт.', 'Rolls it sideways, in degrees. Like the tilt, it can push an edge of the base into the ground.'],
  sculptureBottomOffset: ['Высота основания над грунтом в этой точке, м — над дном или берегом. Минус — скульптура уходит в грунт.', 'Height of the base above the ground at its spot, m — the bed or the shore. Negative sinks it into the ground.'],
  sculptureScale: ['Размер скульптуры. При 0.045 она около 1,4 м в высоту; вдвое больше число — вдвое крупнее.', 'Size of the sculpture. At 0.045 it is about 1.4 m tall; double the number, double the size.'],
  sculptureColor: ['Оттенок чёрного камня. Цвет лишь подкрашивает: тёмный образец не зачернит рисунок, светлый не сделает камень светлым.', 'A tint over the black stone. It only shifts the hue: a dark swatch won’t blacken the pattern, a light one won’t make the stone light.'],
  sculptureLayering: ['Слоистость, как у сланца: полосы с гребнями и бороздами. 0 — сплошной камень; больше — слои заметнее, чаще и неровнее.', 'Slate-like strata: bands of ridges and grooves. 0 is solid stone; higher makes the layers stronger, denser and more irregular.'],
  sculptureLayerScale: ['Частота слоёв: больше — слои тоньше и чаще, меньше — крупные широкие пласты.', 'How fine the layers are: higher gives thinner, more frequent bands, lower gives broad slabs.'],
  sculptureLayerRelief: ['Объём слоёв — насколько гребни и борозды ловят свет. 0 — слои только рисунком. На мокрых местах рельеф сглажен.', 'Depth of the layers — how much ridges and grooves catch the light. 0 leaves them a flat pattern. Wet patches smooth the relief.'],
  sculptureLayerSharpness: ['Форма гребней слоёв: больше — узкие острые рёбра, меньше — мягкие округлые полосы.', 'Shape of the layer ridges: higher gives narrow, sharp edges, lower gives soft rounded bands.'],
  sculptureLayerEdgeChips: ['Мелкие светлые выщербины вдоль кромок слоёв. Видны только при «Слоистости» больше нуля.', 'Small pale chips along the layer edges. They only appear when “Layering” is above zero.'],
  sculptureFracture: ['Раковистый излом, как у обсидиана: гладкие стеклянные грани, рёбра и россыпи мелких сколов. 0 — без излома.', 'Obsidian-like conchoidal fracture: smooth glassy facets, ridges and clusters of small chips. 0 means none.'],
  sculptureFractureScale: ['Размер рисунка излома: больше — грани и сколы мельче и чаще, меньше — крупнее.', 'Size of the fracture pattern: higher makes facets and chips smaller and more frequent, lower makes them larger.'],
  sculptureVeins: ['Тонкие светло-серые жилы в камне: больше — заметнее. На телефоне и слабой графике не рисуются.', 'Thin light-grey veins in the stone; higher makes them stronger. Not drawn on phones or low graphics.'],
  sculptureVeinScale: ['Частота жил: больше — жилы тоньше и гуще, меньше — реже и крупнее.', 'Vein frequency: higher makes veins finer and denser, lower makes them sparser and larger.'],
  sculpturePolish: ['Места, затёртые до блеска, — грани излома и выступы. Больше — таких мест больше, и блестят они сильнее.', 'Spots rubbed to a shine — fracture facets and raised parts. Higher gives more of them and a stronger gloss.'],
  sculptureWearScale: ['Размер пятен потёртости и шершавых участков: больше — пятна мельче и чаще, меньше — крупнее.', 'Size of the worn and rough patches: higher makes them smaller and more frequent, lower makes them larger.'],
  sculptureWetness: ['Мокрые пятна и подтёки: темнее и блестят как зеркало, рельеф под плёнкой сглажен. Больше — мокрого больше.', 'Wet patches and drips: darker, mirror-glossy, the relief smoothed under the film. Higher means more of the stone is wet.'],
  sculptureDryRoughness: ['Шершавость сухого камня: больше — матовее, заметнее тёмные поры и зерно.', 'Roughness of the dry stone: higher is more matte, with more visible dark pores and grain.'],
  sculptureMicroRelief: ['Объём мелкого зерна, пор и сколов на сухих местах — виден вблизи. На телефоне и слабой графике отключён.', 'Depth of the fine grain, pores and chips on dry areas — seen up close. Off on phones and low graphics.'],

  // Лодка
  boatVisible: ['Деревянная лодка на воде с плеском волн о борт. Выключена — исчезает вместе со звуком, чайки на неё не садятся.', 'The wooden boat on the water, with waves lapping at its hull. Off: it disappears with its sound, and gulls stop landing on it.'],
  boatPositionX: ['Где стоит лодка по оси X, м; высоту задаёт вода. Хранится в камере отдельно для Desktop и Mobile, двигать можно и прямо в сцене.', 'Where the boat floats along X, m; the water sets its height. Kept per camera, separately for Desktop and Mobile; you can also drag it in the scene.'],
  boatPositionZ: ['Где стоит лодка по оси Z, м; высоту задаёт вода. Хранится в камере отдельно для Desktop и Mobile, двигать можно и прямо в сцене.', 'Where the boat floats along Z, m; the water sets its height. Kept per camera, separately for Desktop and Mobile; you can also drag it in the scene.'],
  boatYaw: ['Поворот лодки вокруг вертикали, в градусах: куда смотрит нос.', 'Turns the boat around the vertical axis, in degrees: where the bow points.'],
  boatHeightOffset: ['Поднимает лодку над водой или топит глубже: плюс — сидит мельче, минус — глубже. Качка на волнах сохраняется.', 'Raises the boat or sinks it deeper: positive rides higher, negative sits lower. It still rocks on the waves.'],
  boatScale: ['Размер лодки. 0.001 — натуральная величина модели, 0.002 — вдвое больше.', 'Size of the boat. 0.001 is the model’s natural size, 0.002 twice as big.'],
  boatColor: ['Тон дерева: умножается на текстуру досок. Белый — родной цвет дерева, темнее — темнее, цветной — подкрашивает.', 'Wood tone, multiplied over the plank texture. White keeps the wood’s own colour, darker darkens it, a hue tints it.'],
  boatRoughness: ['Матовость дерева: меньше — глянцевее, блики чётче; больше — матовее. Лак поверх настраивается отдельно.', 'Matteness of the wood: lower is glossier with crisper highlights, higher is duller. The varnish on top has its own sliders.'],
  boatReflectionIntensity: ['Сила отражения предметов в воде — не только лодки, но и скульптуры, берега, деревьев. 0 — в воде одно небо, 2 — полное зеркало.', 'How strongly objects mirror in the water — not just the boat: the sculpture, shore and trees too. 0 leaves only the sky, 2 is a full mirror.'],
  boatMetalness: ['Металлический отлив дерева. Действует только до 0.3 — выше без изменений. Тёмные металлические детали не меняются.', 'A metallic sheen on the wood. Works only up to 0.3 — above that nothing changes. The dark metal fittings stay as they are.'],
  boatClearcoat: ['Слой лака поверх дерева — второй, резкий блик. 0 — голое дерево, 1 — полный лак.', 'A varnish layer over the wood — a second, sharp highlight. 0 is bare wood, 1 fully varnished.'],
  boatClearcoatRoughness: ['Гладкость лака: меньше — блик лака резкий и зеркальный, больше — мягкий и размытый.', 'Smoothness of the varnish: lower gives a sharp mirror-like highlight, higher a soft blurred one.'],
  boatCutoutFitWidth: ['Ширина пятна, где вода не рисуется, чтобы в лодке было сухо. Мало — вода видна внутри; много — пропадает вода у бортов.', 'Width of the patch where water is not drawn, keeping the boat dry inside. Too small: water shows inside; too big: water vanishes by the hull.'],
  boatCutoutFitLength: ['Длина того же сухого пятна вдоль лодки. Мало — вода видна внутри у носа и кормы; много — пропадает вода снаружи.', 'Length of the same dry patch along the boat. Too small: water shows inside at bow and stern; too big: water vanishes outside.'],

  // Танкер
  tankerVisible: ['Речной танкер вдали: корпус, след, огни и гул мотора. Выключен — исчезает вместе со звуком.', 'The river tanker in the distance: hull, wake, lights and engine hum. Off: it disappears together with its sound.'],
  tankerTravel: ['Танкер идёт по маршруту. Выключено — стоит на месте и только качается; след и гул мотора всё равно берутся из «Скорости».', 'The tanker sails its route. Off: it holds still and only rocks; the wake and engine sound still follow “Speed”.'],
  tankerWake: ['Светлый клин пены за кормой. Чем выше «Скорость», тем он заметнее; при нуле следа нет.', 'A pale wedge of foam behind the stern. The higher the “Speed”, the stronger it is; at zero there is none.'],
  tankerLights: ['Навигационные и палубные огни: днём приглушены, ночью горят в полную силу; на кормовой мачте мигает маяк.', 'Navigation and deck lights: dimmed by day, full at night; a beacon flashes on the aft mast.'],
  tankerX: ['Середина маршрута по оси запад–восток, м: больше — восточнее. Танкер проходит через эту точку по «Курсу от севера».', 'Middle of the route on the west–east axis, m: higher is further east. The tanker passes this point on its “Bearing from north”.'],
  tankerZ: ['Середина маршрута по оси север–юг, м: больше — южнее, меньше — севернее.', 'Middle of the route on the north–south axis, m: higher is further south, lower further north.'],
  tankerBearing: ['Куда идёт танкер, в градусах по часовой от севера: 0 — на север, 90 — на восток, 180 — на юг.', 'Where the tanker heads, in degrees clockwise from north: 0 north, 90 east, 180 south.'],
  tankerSpeed: ['Скорость хода в узлах (1 узел ≈ 0,5 м/с). От неё же сила следа за кормой и обороты мотора в звуке.', 'Speed in knots (1 knot ≈ 0.5 m/s). It also sets how strong the wake is and the engine’s pitch in the sound.'],
  tankerRouteLength: ['Длина прямого пути; пройдя его, танкер начинает сначала. Держите концы пути за кадром — там он перескакивает.', 'Length of the straight run; at its end the tanker starts over. Keep both ends out of frame — that is where it jumps.'],
  tankerSeaState: ['Собственная качка корпуса на зыби; в ветер и шторм она сама сильнее. 0 — корпус лишь повторяет волну под собой.', 'The hull’s own rolling in the swell; wind and storm make it stronger. At 0 the hull only follows the wave beneath it.'],
  tankerWear: ['Износ краски: пятнистые листы обшивки и бурые потёки ржавчины на корпусе и надстройке.', 'Paint wear: blotchy hull plates and brown rust streaks on the hull and superstructure.'],
  tankerWetness: ['Мокрая полоса у ватерлинии: у воды корпус темнее и блестит. Больше — полоса заметнее.', 'A wet band at the waterline: near the water the hull is darker and glossier. Higher makes it stronger.'],
  tankerRoughness: ['Матовость красной краски борта: меньше — глянцевее, с ясными бликами; больше — матовее.', 'Matteness of the red hull paint: lower is glossier with clear highlights, higher is duller.'],
  tankerLightsIntensity: ['Яркость всех огней танкера; 0 — огни погашены. Днём они всё равно тусклее, чем ночью.', 'Brightness of all the tanker’s lights; 0 switches them off. By day they are still dimmer than at night.'],
  tankerBeaconPeriod: ['Сколько секунд между вспышками белого маяка на кормовой мачте. Красный строб мигает в своём ритме.', 'Seconds between flashes of the white beacon on the aft mast. The red strobe keeps its own rhythm.'],

  // Расстановка
  placedEnabled: ['Показывает или прячет разом все объекты, расставленные вручную: деревья, кусты, камни, модели. Список при этом сохраняется.', 'Shows or hides all hand-placed objects at once: trees, shrubs, rocks, models. The list itself is kept.'],
  placedObjects: ['Какой объект правим: ниже появятся его ползунки. Выбрать можно и щелчком по объекту в сцене. Всего до 48 объектов.', 'Which object you are editing: its sliders appear below. You can also pick it by clicking it in the scene. Up to 48 objects.'],
  'placedObjects[].species': ['Дереву — порода (лох, гребенщик, алыча, вяз, ива, сухостой), ползунки формы встанут по ней. Камню — порода камня. Модели — свет сцены или как в скане.', 'For a tree, the species (oleaster, tamarisk, plum, elm, willow, snag); the form sliders reset to it. For a rock, the stone. For a model, scene light or as scanned.'],
  'placedObjects[].height': ['Высота дерева или куста в метрах; ширину кроны задаёт отдельный ползунок.', 'Height of the tree or shrub in metres; the crown width has its own slider.'],
  'placedObjects[].spread': ['Ширина кроны в метрах: насколько далеко расходятся ветви.', 'Crown width in metres: how far the branches reach out.'],
  'placedObjects[].lean': ['Насколько ветер наклонил дерево: ствол клонится по ветру, крона вытягивается флагом. У вяза, ивы и алычи — слабее.', 'How far the wind has bent the tree: the trunk leans downwind, the crown streams like a flag. Weaker on elm, willow and plum.'],
  'placedObjects[].twist': ['Изгиб ствола вбок, поперёк ветра: 0 — без бокового изгиба, больше — ствол выгнут сильнее.', 'Sideways bend of the trunk, across the wind: 0 means none, higher bends the trunk more.'],
  'placedObjects[].density': ['Густота листвы: меньше — крона сквозная и редкая, больше — плотная.', 'Foliage density: lower gives a sparse, see-through crown, higher a dense one.'],
  'placedObjects[].leafSize': ['Размер листьев — множитель: больше — листья крупнее, крона кажется гуще.', 'Leaf size as a multiplier: higher gives bigger leaves and a fuller-looking crown.'],
  'placedObjects[].deadwood': ['Сколько сухих голых сучьев без листьев: больше — дерево выглядит старым и побитым ветром.', 'How many dry, bare, leafless branches: higher makes the tree look old and wind-beaten.'],
  'placedObjects[].translucency': ['Свечение листвы на просвет, когда солнце за деревом или кустом. 0 — листья глухие.', 'Leaves glowing when the sun is behind the tree or shrub. 0 makes them opaque.'],
  'placedObjects[].x': ['Где стоит объект по оси X, м. Высоту это не меняет — кнопка «На землю» посадит его на грунт.', 'Where the object stands along X, m. Its height does not follow — “Seat on ground” puts it back on the ground.'],
  'placedObjects[].z': ['Где стоит объект по оси Z, м. Высоту это не меняет — кнопка «На землю» посадит его на грунт.', 'Where the object stands along Z, m. Its height does not follow — “Seat on ground” puts it back on the ground.'],
  'placedObjects[].y': ['Высота основания объекта, м (0 — уровень воды). «На землю» ставит его на грунт или на твёрдую модель под ним.', 'Height of the object’s base, m (0 is the water level). “Seat on ground” sets it on the ground or on a solid model beneath.'],
  'placedObjects[].rotation': ['Поворот объекта вокруг вертикали, в градусах: какой стороной он смотрит в камеру.', 'Turns the object around the vertical axis, in degrees: which side faces the camera.'],
  'placedObjects[].scale': ['Общий масштаб поверх собственных размеров объекта. У импортированной модели — от 0.01 до 50: скан бывает в любых единицах.', 'Overall scale on top of the object’s own size. An imported model goes from 0.01 to 50, since scans come in any units.'],
  'placedObjects[].seed': ['Другой случайный вариант той же формы: иначе лягут ветви и листья. На камень не действует — у него «Форма».', 'Another random take on the same form: branches and leaves fall differently. No effect on a rock — it has “Form”.'],
  'placedObjects[].tiltX': ['Наклон модели вперёд-назад, в градусах, считая от её «Поворота».', 'Tilts the model forward or back, in degrees, relative to its “Rotation”.'],
  'placedObjects[].tiltZ': ['Наклон модели вбок, в градусах, считая от её «Поворота».', 'Tilts the model sideways, in degrees, relative to its “Rotation”.'],
  'placedObjects[].hidden': ['Объект остаётся в списке — его можно выбрать, найти кнопкой «Показать» и двигать, — но не рисуется. У модели пропадают и пена, и твёрдость.', 'The object stays in the list — you can pick it, find it with “Frame” and move it — but it is not drawn. A hidden model also loses its foam and solidity.'],
  'placedObjects[].wet': ['Где до модели достаёт море, она темнеет и блестит, как мокрый камень; вода пенится там, где волна набегает на неё.', 'Where the sea reaches the model it turns darker and glossy like wet stone, and the water foams where waves run into it.'],
  'placedObjects[].collision': ['Верх модели становится твёрдой землёй для доски, сёрфера и посадки деревьев: на низкое доска въезжает, о стену останавливается.', 'The model’s top becomes solid ground for the board, the rider and planting: the board rides onto low parts and stops at walls.'],

  // Плоскость
  planeEnabled: ['Ровная пустая земля, чтобы начать сцену с нуля. Освещается сценой и принимает тени. По умолчанию выключена.', 'A flat, empty ground to start a scene from scratch. Lit by the scene and receives shadows. Off by default.'],
  planeSize: ['Сторона квадрата плоскости, м. Она лежит по центру сцены.', 'Side of the square plane, m. It is centred on the scene.'],
  planeHeight: ['Высота плоскости, м: 0 — на уровне воды, минус — под водой.', 'Height of the plane, m: 0 is the water level, negative puts it under water.'],
  planeColor: ['Цвет поверхности плоскости; свет и тени сцены ложатся поверх него.', 'Surface colour of the plane; the scene’s light and shadows fall on top of it.'],
  planeRoughness: ['0 — гладкая, блестит и отражает небо; 1 — матовая, как сухая земля.', '0 is smooth, glossy and mirrors the sky; 1 is matte, like dry earth.'],

  // Чайки
  seagullsEnabled: ['Стая чаек с криками. Им нужна вода: выключена вода — чаек нет, даже если здесь включено.', 'A flock of gulls with their cries. They need water: with the water off there are no gulls, even when this is on.'],
  seagullCount: ['Сколько птиц в стае. На телефоне и слабой графике — не больше пяти.', 'How many birds in the flock. On phones and low graphics, five at most.'],
  seagullFlightActivity: ['Темп полёта: больше — стая летает быстрее и бойчее, меньше — медленно и лениво.', 'Flight tempo: higher makes the flock fly faster and livelier, lower slow and lazy.'],
  seagullLandingDensity: ['Как часто чайки садятся отдохнуть: больше — чаще и раньше. 0 — только летают. Где садиться, задаётся ниже.', 'How often gulls come down to rest: higher is sooner and more often. 0 keeps them flying. Where they land is set below.'],
  seagullPointerInteraction: ['Чайки замечают курсор: летящие сворачивают в сторону, сидящие вспархивают.', 'Gulls notice the cursor: flying ones veer away, perched ones take off.'],
  seagullShootingEnabled: ['Щелчок сбивает чайку — она падает и не летает до перезагрузки сцены. Остальные в испуге разлетаются и возвращаются секунд через 40.', 'A click shoots a gull down — it falls and stays down until the scene reloads. The rest scatter in fright and return after about 40 seconds.'],
  seagullTerritoryRadius: ['Размер круга, над которым летает стая, м. Места посадки на суше и валунах ищутся в этом же круге.', 'Size of the circle the flock flies over, m. Landing spots on land and boulders are found within the same circle.'],
  seagullTerritoryX: ['Центр круга полёта по оси X, м; маршруты и места посадки сдвигаются вместе с ним.', 'Centre of the flight circle along X, m; routes and landing spots move with it.'],
  seagullTerritoryZ: ['Центр круга полёта по оси Z, м; маршруты и места посадки сдвигаются вместе с ним.', 'Centre of the flight circle along Z, m; routes and landing spots move with it.'],
  seagullAltitudeMin: ['Самая низкая высота полёта над водой, м: при малых значениях чайки проносятся над самой водой.', 'Lowest flight height above the water, m: small values let gulls skim the surface.'],
  seagullAltitudeMax: ['Самая большая высота полёта над водой, м. Маршруты растягиваются между нижней и верхней высотой.', 'Highest flight height above the water, m. The routes stretch between the low and high limits.'],
  seagullPerchTerrain: ['Садятся на сухую ровную землю в пределах территории: пляж, невысокие уступы.', 'They land on dry, level ground within the territory: beach, low ledges.'],
  seagullPerchRocks: ['Садятся на макушки валунов в пределах территории.', 'They land on boulder tops within the territory.'],
  seagullPerchObjects: ['Садятся на лодку и скульптуру (на расставленные вручную объекты — нет).', 'They land on the boat and the sculpture (not on hand-placed objects).'],
  seagullPerchCount: ['Сколько мест посадки искать на суше и валунах; места не ближе 2,4 м друг к другу. Лодка и скульптура сюда не входят.', 'How many landing spots to find on land and boulders, at least 2.4 m apart. The boat and sculpture are not counted here.'],

  // Рыбы
  fishEnabled: ['Рыбы под водой: щука, окуни и косяк плотвы. Видны сквозь воду; выключена вода — рыб нет.', 'Fish under the water: a pike, perch and a school of roach. Seen through the water; with the water off there are none.'],
  fishPointerInteraction: ['Рыбы пугаются курсора: рыба под ним бросается прочь, испуг волной передаётся соседям.', 'Fish are scared by the cursor: the one under it darts away and the fright ripples to its neighbours.'],
  fishCount: ['Сколько рыб: одна щука, остальные окуни и плотва. Качество графики ограничивает число: на среднем до 30, на слабом до 14.', 'How many fish: one pike, the rest perch and roach. Graphics quality caps it: up to 30 on medium, 14 on low.'],
  fishSchooling: ['Насколько окуни и плотва держатся вместе и плывут одной лентой по общему пути. 0 — почти каждая сама по себе. Щука всегда одна.', 'How closely perch and roach keep together and swim as one ribbon along a shared path. 0 is nearly every fish for itself. The pike stays alone.'],
  fishActivity: ['Бодрость рыб: больше — плывут быстрее и чаще бьют хвостом, меньше — медленно дрейфуют.', 'How lively the fish are: higher swims faster with quicker tail beats, lower drifts slowly.'],
  fishDepthBand: ['Насколько глубоко рыбы уходят от поверхности: 0 — тонким слоем у самой поверхности, 100% — по всей толще до дна.', 'How deep the fish go below the surface: 0 keeps them in a thin layer just under it, 100% spreads them down to the bed.'],

  // Кувшинки
  liliesVisible: ['Плавающие листья кувшинок на воде. Им нужна вода: выключена вода — их нет, даже если здесь включено.', 'Floating lily pads on the water. They need water: with the water off there are none, even when this is on.'],
  surfacePlantAmount: ['Сколько листьев на воде — доля от наибольшего числа, которое зависит от качества графики.', 'How many pads float on the water — a share of the maximum, which depends on the graphics quality.'],
  surfacePlantClustering: ['0 — листья рассыпаны по всему пятну, 100% — собраны в плотные островки.', '0 scatters the pads over the whole patch, 100% gathers them into dense islands.'],
  surfacePlantCenterX: ['Сдвигает всё пятно кувшинок вдоль оси X, м. Где пятно заходит на сушу, листьев нет.', 'Moves the whole lily patch along X, m. Where the patch reaches land there are no pads.'],
  surfacePlantCenterZ: ['Сдвигает всё пятно кувшинок вдоль оси Z, м. Где пятно заходит на сушу, листьев нет.', 'Moves the whole lily patch along Z, m. Where the patch reaches land there are no pads.'],
  surfacePlantRadius: ['Размер пятна кувшинок, м: больше — то же число листьев расходится шире и реже.', 'Size of the lily patch, m: larger spreads the same number of pads wider and thinner.'],
  surfacePlantSize: ['Ширина листа, м; листья разные — от половины до полутора этого размера.', 'Pad width, m; pads vary from half to one and a half times this size.'],
  surfacePlantFloatOffset: ['Насколько лист приподнят над водой, м. Минус — лист притоплен, и вода заливает его края.', 'How high the pad rides above the water, m. Negative sinks it so the water washes over its edges.'],
  surfacePlantStiffness: ['0 — лист гнётся по волне под ним; 100% — остаётся плоским диском, и крутая волна захлёстывает его край.', '0 lets the pad bend with the wave beneath it; 100% keeps it a flat disc, so a steep wave laps over its edge.'],
  surfacePlantColor: ['Подкрашивает родную окраску листьев выбранным цветом — мягко: рисунок и тон текстуры остаются.', 'Tints the pads’ own colouring with this colour — gently: the texture’s pattern and tone remain.'],
  surfacePlantSaturation: ['Сочность цвета листьев: 0 — серые, 100% — как есть, выше — ярче.', 'Colour richness of the pads: 0 is grey, 100% as is, higher more vivid.'],
  surfacePlantTranslucency: ['Свечение листа на просвет, когда солнце или фонарик курсора светят сзади. Больше — ярче жёлто-зелёный просвет.', 'The pad glowing when the sun or the cursor torch shines from behind. Higher gives a brighter yellow-green glow.'],
  surfacePlantReflection: ['Влажный блеск листьев: блик солнца и отражение неба и берега. 0 — листья матовые.', 'The wet sheen of the pads: sun glints and reflections of the sky and shore. 0 makes them matte.'],
  plantAoStrength: ['Тень у основания подводных водорослей, где нить входит в дно: больше — темнее. На кувшинки не влияет.', 'Shade at the base of the underwater algae, where strands meet the bed: higher is darker. Does not affect the lilies.'],

  // Водоросли
  algaeVisible: ['Подводные водоросли на дне, видны сквозь воду. Им нужна вода: выключена вода — их нет, даже если здесь включено.', 'Underwater algae on the bed, seen through the water. They need water: with the water off there are none, even when this is on.'],
  underwaterAlgaeAmount: ['Сколько нитей в зарослях — доля от наибольшего числа, которое зависит от качества графики.', 'How many strands grow — a share of the maximum, which depends on the graphics quality.'],
  underwaterAlgaeDensity: ['Множитель числа нитей поверх количества. На высоком качестве графики до ×4, на среднем до ×2, на слабом не действует.', 'Multiplies the number of strands on top of the amount. Up to ×4 on high graphics, ×2 on medium, no effect on low.'],
  underwaterAlgaeCenterX: ['Сдвигает всё пятно водорослей вдоль оси X, м. На суше и у самого уреза нитей нет.', 'Moves the whole algae patch along X, m. No strands grow on land or right at the waterline.'],
  underwaterAlgaeCenterZ: ['Сдвигает всё пятно водорослей вдоль оси Z, м. На суше и у самого уреза нитей нет.', 'Moves the whole algae patch along Z, m. No strands grow on land or right at the waterline.'],
  underwaterAlgaeRadius: ['Размер пятна водорослей, м: больше — то же число нитей расходится шире и реже.', 'Size of the algae patch, m: larger spreads the same number of strands wider and thinner.'],
  underwaterAlgaeLength: ['Длина нитей, м; у разных видов длиннее или короче. Из воды не торчат: на мелком месте короче.', 'Strand length, m; some kinds grow longer or shorter. They never break the surface: shallow water shortens them.'],
  underwaterAlgaeWidth: ['Ширина нитей — множитель: меньше 1 — тоньше, больше — широкие ленты.', 'Strand width as a multiplier: below 1 is thinner, above gives broad ribbons.'],
  underwaterAlgaeSway: ['Колыхание в воде: больше — нити сильнее раскачиваются и трепещут кончиками; 0 — замирают.', 'Sway in the water: higher makes strands rock more with fluttering tips; 0 freezes them.'],
  underwaterAlgaeFlowDirection: ['Куда течёт вода у дна, в градусах по кругу: в эту сторону клонятся нити.', 'Which way the current runs along the bed, in degrees around the circle: the strands lean that way.'],
  underwaterAlgaeFlowStrength: ['Насколько течение пригибает заросли: 0 — стоят прямо, больше — ложатся по течению.', 'How far the current bends the meadow: 0 stands it upright, higher lays it down with the flow.'],
  underwaterAlgaeSpeciesMix: ['Смесь трёх видов — узкие ленты, широкие листья, длинные тонкие нити. 0 — только узкие ленты.', 'Mix of three kinds — narrow ribbons, broad blades, long fine threads. 0 gives only narrow ribbons.'],
  underwaterAlgaePatchiness: ['0 — нити ровно по всему пятну; больше — собраны в густые куртины с тенью у корней.', '0 spreads strands evenly over the patch; higher gathers them into dense clumps with shade at the roots.'],
  underwaterAlgaeColor: ['Основной цвет водорослей; каждый вид добавляет к нему свой оттенок.', 'Base colour of the algae; each kind adds its own shade to it.'],
  underwaterAlgaeSaturation: ['Сочность цвета водорослей: 0 — серые, 100% — как есть, выше — ярче.', 'Colour richness of the algae: 0 is grey, 100% as is, higher more vivid.'],
};
