// Подсказки «?» к окружению участка — оно есть только в проекте «Участок»,
// поэтому справочник (собран на редакторе сайта) его не видит: ключи
// перечислены в CONDITIONAL проверки. Значение — [по-русски, in English].
export default {
    surroundingsEnabled: ['Окружение участка — дома, дороги, рельеф и деревья вокруг модели по карте OpenStreetMap. Выключено — модель стоит одна, данные в проекте остаются.', 'The plot’s surroundings — buildings, roads, relief and trees around the model from OpenStreetMap. Off: the model stands alone; the data stays in the project.'],
    surroundingsRadius: ['Сколько карты вокруг участка, м. Меньше загруженного — обрезается сразу; больше — нажмите «Обновить окружение», и недостающее догрузится.', 'How much map around the plot, m. Less than loaded trims at once; more needs «Reload surroundings» to fetch the rest.'],
    surroundingsBuildings: ['Дома коробками: высота из карты, по этажам (3 м на этаж) или оценкой по типу здания. В круге участка домов нет — там модель SketchUp.', 'Buildings as blocks: height from the map, by storeys (3 m each) or estimated from the building type. None inside the plot circle — the SketchUp model is there.'],
    surroundingsTrees: ['Деревья, отмеченные на карте, и лес: площади леса засеваются деревом на каждые 7 м. Деревья макетные — ствол и шар кроны.', 'Trees marked on the map, and woods: forest areas are sown with a tree every 7 m. Model-style trees — a trunk and a round crown.'],
    surroundingsFences: ['Заборы, стены и живые изгороди соседей по карте. Высота, если карта её не знает: забор 1,6 м, стена 2,2 м, изгородь 1,4 м.', 'Neighbours’ fences, walls and hedges from the map. Height when the map does not know it: fence 1.6 m, wall 2.2 m, hedge 1.4 m.'],
    surroundingsRelief: ['Сила рельефа: 1 — как на местности (съёмка SRTM, шаг около 30 м), 0 — всё ровно, 2 — вдвое круче. У самого участка земля всегда ровная.', 'Relief strength: 1 is true to the ground (SRTM survey, about 30 m apart), 0 flattens it, 2 doubles it. Right at the plot the ground stays flat.'],
    northAngle: ['Где истинный север: градусы по часовой стрелке от зелёной оси SketchUp. Поворачивайте, пока дороги и заборы карты не лягут на модель.', 'Where true north is: degrees clockwise from SketchUp’s green axis. Turn it until the map’s roads and fences line up with the model.'],
    surroundingsOffsetX: ['Сдвиг карты вдоль оси X модели, м: точка адреса редко попадает ровно в середину модели. Двигайте, пока соседние заборы и дороги не совпадут.', 'Shifts the map along the model’s X axis, m: the address point rarely hits the middle of the model. Move it until the neighbours’ fences and roads match.'],
    surroundingsOffsetZ: ['Сдвиг карты вдоль оси Z модели, м: вместе со сдвигом X сажает карту на модель точно.', 'Shifts the map along the model’s Z axis, m: together with Shift X it seats the map on the model exactly.'],
    surroundingsClear: ['Радиус вокруг точки карты, м, где нет чужих домов, деревьев и заборов, а земля ровная — там стоит модель участка. Дальше земля плавно уходит в рельеф.', 'Radius around the map point, m, with no other buildings, trees or fences and flat ground — the plot model stands there. Beyond it the ground eases into the relief.'],
    surroundingsBuildingColor: ['Цвет домов окружения. По умолчанию светлый, как у макета: окружение не спорит с проектом.', 'Colour of the surrounding buildings. Light and model-like by default, so the context does not compete with the design.'],
    surroundingsGroundColor: ['Цвет земли вокруг: кварталы, дворы, пустыри. От него же светлеют тропинки, поля и огороды.', 'Colour of the ground around: blocks, yards, wasteland. Paths, fields and allotments are blended from it too.'],
    surroundingsRoadColor: ['Цвет дорог: главные улицы — этим цветом, переулки чуть светлее, тротуары и тропинки — наполовину к земле.', 'Colour of the roads: main streets take it, lanes a little lighter, pavements and paths halfway to the ground.'],
    surroundingsGreenColor: ['Цвет парков, газонов и скверов; лес и деревья — чуть темнее, поля и огороды — ближе к земле.', 'Colour of parks, lawns and squares; woods and trees a little darker, fields and allotments closer to the ground.'],
    surroundingsWaterColor: ['Цвет рек, ручьёв, прудов и водохранилищ на земле окружения.', 'Colour of rivers, streams, ponds and reservoirs on the ground around.'],
};
