import assert from 'node:assert/strict';
import * as THREE from 'three';
import { connectedFace, materialMeshKey, paintTargets, targetAt, targetHasMaterial, targetOverride } from './selection.js';
import { normalizeMaterialSettings } from './settings.js';
import { boxUvGeometry, splitFaces } from './modelMaterials.js';
import { surfaceBasis } from './projection.js';

const root = new THREE.Group(), geometry = new THREE.BoxGeometry(2, 1, 3), material = new THREE.MeshStandardMaterial({ name: 'concrete' });
geometry.clearGroups();
root.userData.materialModel = 'building-v1';
const a = new THREE.Mesh(geometry, material), b = new THREE.Mesh(geometry, material); root.add(a, b);
assert.notEqual(materialMeshKey(a, root), materialMeshKey(b, root), 'instances sharing geometry have separate addresses');
assert.deepEqual(connectedFace(geometry, 0), [0, 1], 'one click selects a polygon, not one triangle or all six sides');
const first = targetAt({ placedId: 'building', object: a, faceIndex: 0 }, root);
const second = targetAt({ placedId: 'building', object: a, faceIndex: 4 }, root);
const look = { material: 'stone', tile: 1.2, tileY: 0.6, normal: 1, roughness: 1, projection: 'slope', offsetU: 0.12 };
let settings = paintTargets({}, [first, second], 'face', look);
settings = normalizeMaterialSettings({ modelMaterials: settings }).modelMaterials;
assert.equal(settings.building.concrete.faces[0].targets.length, 2, 'multi-face assignment survives normalization');
assert.equal(targetOverride(settings, first, 'face').offsetU, 0.12);
assert.equal(targetHasMaterial(settings, first, 'face', 'stone'), true);
assert.equal(targetHasMaterial(settings, { ...first, triangles: null }, 'component', 'stone'), false, 'painting one side does not disable Apply for the rest of the component');
assert.equal(targetOverride(settings, { ...first, meshKey: '1' }, 'face'), settings.building.concrete, 'component copy stays unchanged');
const split = splitFaces(geometry, new THREE.Matrix4(), settings.building.concrete.faces, [], '0', 'building-v1');
assert.equal(splitFaces(geometry, new THREE.Matrix4(), settings.building.concrete.faces, [], '0', 'building-v2'), null, 'a replacement model never inherits triangle addresses from the previous file');
assert.equal(split.groups.find((group) => group.materialIndex === 1).count, 12, 'only the four chosen triangles are painted');
a.userData.faceSplit = { geometry, material }; a.geometry = split; a.material = [material, new THREE.MeshStandardMaterial()];
const regroupedIndex = split.userData.sourceTriangles.indexOf(4);
assert.deepEqual(targetAt({ placedId: 'building', object: a, faceIndex: regroupedIndex }, root).triangles, [4, 5], 'picking a painted face resolves the original triangle order');
settings = paintTargets(settings, [first], 'face', { ...look, material: 'metal' });
assert.equal(targetOverride(settings, first, 'face').material, 'metal');
assert.equal(targetOverride(settings, second, 'face').material, 'stone');
settings = paintTargets(settings, [first], 'face', null);
assert.ok(!targetOverride(settings, first, 'face').material, 'restore removes paint on only the selected polygon');
assert.equal(targetOverride(settings, second, 'face').material, 'stone');
const whole = paintTargets({ building: { concrete: look } }, [first], 'material', null);
assert.deepEqual(whole, {}, 'whole-material restore actually removes the override');
const component = paintTargets({}, [{ ...first, triangles: null }], 'component', look);
const partial = paintTargets(component, [first], 'face', null);
assert.equal(partial.building.concrete.faces[0].targets[0].triangles.length, 10, 'restoring a face of a painted component leaves its other sides');

const normal = new THREE.Vector3(0.25, 0.7, 0.65).normalize(), [u, v] = surfaceBasis(normal, 'slope');
assert.ok(Math.abs(u.dot(normal)) < 1e-9 && Math.abs(v.dot(normal)) < 1e-9 && Math.abs(u.dot(v)) < 1e-9);
assert.ok(Math.abs(u.y) < 1e-9, 'roof seams cross contours and follow the slope');
assert.ok(Math.abs(v.length() - 1) < 1e-9, 'slope coordinates preserve metres, without plan-view stretching');
const plane = new THREE.PlaneGeometry(2, 2).rotateX(-Math.PI / 2);
const left = boxUvGeometry(plane, new THREE.Matrix4().makeTranslation(0, 0, 0));
const right = boxUvGeometry(plane, new THREE.Matrix4().makeTranslation(2, 0, 0));
const edgeUvs = (g, x) => {
    const out = [];
    for (let i = 0; i < g.attributes.position.count; i++) if (Math.abs(g.attributes.position.getX(i) - x) < 1e-8) out.push([g.attributes.uv.getX(i), g.attributes.uv.getY(i)]);
    return [...new Set(out.map(JSON.stringify))].sort();
};
assert.deepEqual(edgeUvs(left, 1), edgeUvs(right, -1), 'adjacent mesh instances share the same UV phase at the boundary');
console.log('material selection: polygon adjacency, shared instances, regrouped picking, multi-selection, restore, persistence, roof metric basis and continuous projection — ok');
