// Look-dev presets of the laboratory. The material itself is the product's
// (components/effects/water/blackStoneMaterial.js); 'hybrid' equals its defaults.
export const BLACK_STONE_PRESETS = Object.freeze({
  hybrid: Object.freeze({
    layering: 0.99,
    layerScale: 2.2,
    layerRelief: 1,
    layerSharpness: 1,
    layerEdgeChips: 0.78,
    fracture: 0.85,
    fractureScale: 3.15,
    veins: 0.19,
    veinScale: 3.9,
    polish: 0.71,
    wearScale: 2.3,
    wetness: 0.98,
    dryRoughness: 0.78,
    microRelief: 0.78,
  }),
  slate: Object.freeze({
    layering: 0.94,
    layerScale: 2.65,
    layerRelief: 0.9,
    layerSharpness: 0.82,
    layerEdgeChips: 0.68,
    fracture: 0.55,
    fractureScale: 3.1,
    veins: 0.18,
    veinScale: 2.8,
    polish: 0.16,
    wearScale: 2.3,
    wetness: 0.08,
    dryRoughness: 0.9,
    microRelief: 0.78,
  }),
  obsidian: Object.freeze({
    layering: 0.25,
    layerScale: 1.35,
    layerRelief: 0.42,
    layerSharpness: 0.86,
    layerEdgeChips: 0.3,
    fracture: 0.88,
    fractureScale: 2.1,
    veins: 0.1,
    veinScale: 3.1,
    polish: 0.74,
    wearScale: 1.5,
    wetness: 0.18,
    dryRoughness: 0.38,
    microRelief: 0.3,
  }),
  wet: Object.freeze({
    layering: 0.7,
    layerScale: 2.05,
    layerRelief: 0.68,
    layerSharpness: 0.6,
    layerEdgeChips: 0.48,
    fracture: 0.68,
    fractureScale: 2.45,
    veins: 0.28,
    veinScale: 2.3,
    polish: 0.5,
    wearScale: 2.0,
    wetness: 0.78,
    dryRoughness: 0.66,
    microRelief: 0.58,
  }),
});

